In [9]:
# Import the data
import numpy as np
import pandas as pd

USacc_df = pd.read_csv('US_Accidents_June20.csv')
NJacc_df = USacc_df[USacc_df['State']=='NJ']
NJacc_df.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
194254,A-194256,MapQuest,201.0,2,2016-11-30 16:37:24,2016-11-30 17:22:05,40.775616,-74.237305,NaN,NaN,...,False,False,False,False,True,False,Night,Day,Day,Day
194270,A-194272,MapQuest,201.0,2,2016-11-30 17:11:50,2016-11-30 17:56:38,40.944626,-74.100800,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Day,Day
194271,A-194273,MapQuest,201.0,2,2016-11-30 17:13:28,2016-11-30 18:13:14,40.846260,-74.042770,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Day,Day
194280,A-194282,MapQuest,241.0,3,2016-11-30 17:29:30,2016-11-30 18:14:16,40.641262,-74.205650,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Day,Day
194299,A-194301,MapQuest,203.0,2,2016-11-30 19:10:49,2016-11-30 20:10:39,40.957714,-73.975098,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Night,Night

In [10]:
# Convert Start_Time and End_Time to datetypes
NJacc_df['Start_Time'] = pd.to_datetime(NJacc_df['Start_Time'], errors='coerce')
NJacc_df['End_Time'] = pd.to_datetime(NJacc_df['End_Time'], errors='coerce')

# Extract year, month, day, hour, weekday and time_duration information
NJacc_df['Year']=NJacc_df['Start_Time'].dt.year
NJacc_df['Month']=NJacc_df['Start_Time'].dt.strftime('%b')
NJacc_df['Day']=NJacc_df['Start_Time'].dt.day
NJacc_df['Hour']=NJacc_df['Start_Time'].dt.hour
NJacc_df['Weekday']=NJacc_df['Start_Time'].dt.strftime('%a')

# Extract the amount of time in the unit of minutes for each accident, round to the nearest integer
total_duration='Time_Duration(min)'
NJacc_df[total_duration]=round((NJacc_df['End_Time']-NJacc_df['Start_Time'])/np.timedelta64(1,'m'))

# Check the dataframe
NJacc_df.head()

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight,Year,Month,Day,Hour,Weekday,Time_Duration(min)
194254,A-194256,MapQuest,201.0,2,2016-11-30 16:37:24,2016-11-30 17:22:05,40.775616,-74.237305,NaN,NaN,...,Night,Day,Day,Day,2016,Nov,30,16,Wed,45.0
194270,A-194272,MapQuest,201.0,2,2016-11-30 17:11:50,2016-11-30 17:56:38,40.944626,-74.100800,NaN,NaN,...,Night,Night,Day,Day,2016,Nov,30,17,Wed,45.0
194271,A-194273,MapQuest,201.0,2,2016-11-30 17:13:28,2016-11-30 18:13:14,40.846260,-74.042770,NaN,NaN,...,Night,Night,Day,Day,2016,Nov,30,17,Wed,60.0
194280,A-194282,MapQuest,241.0,3,2016-11-30 17:29:30,2016-11-30 18:14:16,40.641262,-74.205650,NaN,NaN,...,Night,Night,Day,Day,2016,Nov,30,17,Wed,45.0
194299,A-194301,MapQuest,203.0,2,2016-11-30 19:10:49,2016-11-30 20:10:39,40.957714,-73.975098,NaN,NaN,...,Night,Night,Night,Night,2016,Nov,30,19,Wed,60.0

## Predict the accident severity with different supervised machine learning algorithms

#### Drop rows with negative time

In [11]:
# Drop the rows with td<0
negtime_outliers=NJacc_df[total_duration]<=0

# Set outliers to NAN
NJacc_df[negtime_outliers] = np.nan

# Drop rows with negative td
NJacc_df.dropna(subset=[total_duration],axis=0,inplace=True)

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

#### Replace outliers with median values.

In [12]:
n=3

median = NJacc_df[total_duration].median()
std = NJacc_df[total_duration].std()
outliers = (NJacc_df[total_duration] - median).abs() > std*n

# Set outliers to NAN
NJacc_df[outliers] = np.nan

# Fill NAN with median
NJacc_df[total_duration].fillna(median, inplace=True)

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [13]:
feature_lst=['Source','TMC','Severity','Start_Lng','Start_Lat','Distance(mi)','Side','City','County','State','Timezone','Temperature(F)','Humidity(%)','Pressure(in)', 'Visibility(mi)', 'Wind_Direction','Weather_Condition','Amenity','Bump','Crossing','Give_Way','Junction','No_Exit','Railway','Roundabout','Station','Stop','Traffic_Calming','Traffic_Signal','Turning_Loop','Sunrise_Sunset','Hour','Weekday', 'Time_Duration(min)']

In [17]:
NJacc_feature_df=NJacc_df[feature_lst]
NJacc_feature_df.dropna(subset=NJacc_feature_df.columns[NJacc_feature_df.isnull().mean()!=0], how='any', axis=0, inplace=True)
NJacc_feature_df.shape

/projects/community/py-data-science-stack/5.1.0/kp807/envs/fastai/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

(34433, 34)

#### Create dummy variable

In [18]:
NJacc_dummy = pd.get_dummies(NJacc_feature_df,drop_first=True)

#### Train and test split

In [19]:
from sklearn.model_selection import train_test_split

# Set the target for the prediction
target='Severity'

# set X and y
y = NJacc_dummy[target]
X = NJacc_dummy.drop(target, axis=1)

# Split the data set into training and testing data sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=21, stratify=y)

In [22]:
from sklearn.neighbors import KNeighborsClassifier

# Create a k-NN classifier with 5 neighbors
knn = KNeighborsClassifier(n_neighbors=5)

# Fit the classifier to the data
knn.fit(X_train,y_train)

# Predict the labels for the training data X
y_pred = knn.predict(X_test)

# Get the accuracy score
accuracy=accuracy_score(y_test, y_pred)


print('KNN accuracy_score: {:.3f}.'.format(accuracy))

KNN accuracy_score: 0.631.

In [23]:
from sklearn.tree import DecisionTreeClassifier

# Instantiate dt_entropy, set 'entropy' as the information criterion
decisiontree = DecisionTreeClassifier(max_depth=8, criterion='entropy', random_state=1)


# Fit dt_entropy to the training set
decisiontree.fit(X_train, y_train)

# Use dt_entropy to predict test set labels
y_pred= decisiontree.predict(X_test)

# Evaluate accuracy_entropy
accuracy = accuracy_score(y_test, y_pred)


# Print accuracy_entropy
print('Decision Tree accuracy_score: {:.3f}.'.format(accuracy))

Decision Tree accuracy_score: 0.747.

In [26]:
# Random Forest algorithm
from sklearn.ensemble import RandomForestClassifier


clf=RandomForestClassifier(n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)


# Get the accuracy score
accuracy=accuracy_score(y_test, y_pred)


# Model Accuracy, how often is the classifier correct?
print("Randon forest algorithm accuracy_score: {:.3f}.".format(accuracy))

Randon forest algorithm accuracy_score: 0.869.

In [25]:
# Adaboost algorithm

from sklearn.ensemble import AdaBoostClassifier


clf=AdaBoostClassifier(base_estimator=decisiontree, n_estimators=100)

#Train the model using the training sets y_pred=clf.predict(X_test)
clf.fit(X_train,y_train)

y_pred=clf.predict(X_test)


# Get the accuracy score
accuracy=accuracy_score(y_test, y_pred)


# Model Accuracy, how often is the classifier correct?
print("AdaBoost algorithm accuracy_score: {:.3f}.".format(accuracy))

AdaBoost algorithm accuracy_score: 0.752.